/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlotSizesPricingRouteImport } from './routes/plot-sizes-pricing'
import { Route as Phase2OverviewRouteImport } from './routes/phase-2-overview'
import { Route as MasterPlanRouteImport } from './routes/master-plan'
import { Route as LocationConnectivityRouteImport } from './routes/location-connectivity'
import { Route as InvestmentBenefitsRouteImport } from './routes/investment-benefits'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DownloadBrochureRouteImport } from './routes/download-brochure'
import { Route as DevelopmentUpdatesRouteImport } from './routes/development-updates'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as BookSiteVisitRouteImport } from './routes/book-site-visit'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AboutSukiNihonPhase2AlibagRouteImport } from './routes/about-suki-nihon-phase-2-alibag'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotSizesPricingRoute = PlotSizesPricingRouteImport.update({
  id: '/plot-sizes-pricing',
  path: '/plot-sizes-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase2OverviewRoute = Phase2OverviewRouteImport.update({
  id: '/phase-2-overview',
  path: '/phase-2-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterPlanRoute = MasterPlanRouteImport.update({
  id: '/master-plan',
  path: '/master-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationConnectivityRoute = LocationConnectivityRouteImport.update({
  id: '/location-connectivity',
  path: '/location-connectivity',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentBenefitsRoute = InvestmentBenefitsRouteImport.update({
  id: '/investment-benefits',
  path: '/investment-benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadBrochureRoute = DownloadBrochureRouteImport.update({
  id: '/download-brochure',
  path: '/download-brochure',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentUpdatesRoute = DevelopmentUpdatesRouteImport.update({
  id: '/development-updates',
  path: '/development-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSiteVisitRoute = BookSiteVisitRouteImport.update({
  id: '/book-site-visit',
  path: '/book-site-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSukiNihonPhase2AlibagRoute =
  AboutSukiNihonPhase2AlibagRouteImport.update({
    id: '/about-suki-nihon-phase-2-alibag',
    path: '/about-suki-nihon-phase-2-alibag',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-suki-nihon-phase-2-alibag': typeof AboutSukiNihonPhase2AlibagRoute
  '/amenities': typeof AmenitiesRoute
  '/blogs': typeof BlogsRoute
  '/book-site-visit': typeof BookSiteVisitRoute
  '/contact-us': typeof ContactUsRoute
  '/development-updates': typeof DevelopmentUpdatesRoute
  '/download-brochure': typeof DownloadBrochureRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/investment-benefits': typeof InvestmentBenefitsRoute
  '/location-connectivity': typeof LocationConnectivityRoute
  '/master-plan': typeof MasterPlanRoute
  '/phase-2-overview': typeof Phase2OverviewRoute
  '/plot-sizes-pricing': typeof PlotSizesPricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-suki-nihon-phase-2-alibag': typeof AboutSukiNihonPhase2AlibagRoute
  '/amenities': typeof AmenitiesRoute
  '/blogs': typeof BlogsRoute
  '/book-site-visit': typeof BookSiteVisitRoute
  '/contact-us': typeof ContactUsRoute
  '/development-updates': typeof DevelopmentUpdatesRoute
  '/download-brochure': typeof DownloadBrochureRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/investment-benefits': typeof InvestmentBenefitsRoute
  '/location-connectivity': typeof LocationConnectivityRoute
  '/master-plan': typeof MasterPlanRoute
  '/phase-2-overview': typeof Phase2OverviewRoute
  '/plot-sizes-pricing': typeof PlotSizesPricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-suki-nihon-phase-2-alibag': typeof AboutSukiNihonPhase2AlibagRoute
  '/amenities': typeof AmenitiesRoute
  '/blogs': typeof BlogsRoute
  '/book-site-visit': typeof BookSiteVisitRoute
  '/contact-us': typeof ContactUsRoute
  '/development-updates': typeof DevelopmentUpdatesRoute
  '/download-brochure': typeof DownloadBrochureRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/investment-benefits': typeof InvestmentBenefitsRoute
  '/location-connectivity': typeof LocationConnectivityRoute
  '/master-plan': typeof MasterPlanRoute
  '/phase-2-overview': typeof Phase2OverviewRoute
  '/plot-sizes-pricing': typeof PlotSizesPricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-suki-nihon-phase-2-alibag'
    | '/amenities'
    | '/blogs'
    | '/book-site-visit'
    | '/contact-us'
    | '/development-updates'
    | '/download-brochure'
    | '/faqs'
    | '/gallery'
    | '/investment-benefits'
    | '/location-connectivity'
    | '/master-plan'
    | '/phase-2-overview'
    | '/plot-sizes-pricing'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-suki-nihon-phase-2-alibag'
    | '/amenities'
    | '/blogs'
    | '/book-site-visit'
    | '/contact-us'
    | '/development-updates'
    | '/download-brochure'
    | '/faqs'
    | '/gallery'
    | '/investment-benefits'
    | '/location-connectivity'
    | '/master-plan'
    | '/phase-2-overview'
    | '/plot-sizes-pricing'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about-suki-nihon-phase-2-alibag'
    | '/amenities'
    | '/blogs'
    | '/book-site-visit'
    | '/contact-us'
    | '/development-updates'
    | '/download-brochure'
    | '/faqs'
    | '/gallery'
    | '/investment-benefits'
    | '/location-connectivity'
    | '/master-plan'
    | '/phase-2-overview'
    | '/plot-sizes-pricing'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutSukiNihonPhase2AlibagRoute: typeof AboutSukiNihonPhase2AlibagRoute
  AmenitiesRoute: typeof AmenitiesRoute
  BlogsRoute: typeof BlogsRoute
  BookSiteVisitRoute: typeof BookSiteVisitRoute
  ContactUsRoute: typeof ContactUsRoute
  DevelopmentUpdatesRoute: typeof DevelopmentUpdatesRoute
  DownloadBrochureRoute: typeof DownloadBrochureRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  InvestmentBenefitsRoute: typeof InvestmentBenefitsRoute
  LocationConnectivityRoute: typeof LocationConnectivityRoute
  MasterPlanRoute: typeof MasterPlanRoute
  Phase2OverviewRoute: typeof Phase2OverviewRoute
  PlotSizesPricingRoute: typeof PlotSizesPricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plot-sizes-pricing': {
      id: '/plot-sizes-pricing'
      path: '/plot-sizes-pricing'
      fullPath: '/plot-sizes-pricing'
      preLoaderRoute: typeof PlotSizesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-2-overview': {
      id: '/phase-2-overview'
      path: '/phase-2-overview'
      fullPath: '/phase-2-overview'
      preLoaderRoute: typeof Phase2OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-plan': {
      id: '/master-plan'
      path: '/master-plan'
      fullPath: '/master-plan'
      preLoaderRoute: typeof MasterPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-connectivity': {
      id: '/location-connectivity'
      path: '/location-connectivity'
      fullPath: '/location-connectivity'
      preLoaderRoute: typeof LocationConnectivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-benefits': {
      id: '/investment-benefits'
      path: '/investment-benefits'
      fullPath: '/investment-benefits'
      preLoaderRoute: typeof InvestmentBenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-brochure': {
      id: '/download-brochure'
      path: '/download-brochure'
      fullPath: '/download-brochure'
      preLoaderRoute: typeof DownloadBrochureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development-updates': {
      id: '/development-updates'
      path: '/development-updates'
      fullPath: '/development-updates'
      preLoaderRoute: typeof DevelopmentUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-site-visit': {
      id: '/book-site-visit'
      path: '/book-site-visit'
      fullPath: '/book-site-visit'
      preLoaderRoute: typeof BookSiteVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-suki-nihon-phase-2-alibag': {
      id: '/about-suki-nihon-phase-2-alibag'
      path: '/about-suki-nihon-phase-2-alibag'
      fullPath: '/about-suki-nihon-phase-2-alibag'
      preLoaderRoute: typeof AboutSukiNihonPhase2AlibagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutSukiNihonPhase2AlibagRoute: AboutSukiNihonPhase2AlibagRoute,
  AmenitiesRoute: AmenitiesRoute,
  BlogsRoute: BlogsRoute,
  BookSiteVisitRoute: BookSiteVisitRoute,
  ContactUsRoute: ContactUsRoute,
  DevelopmentUpdatesRoute: DevelopmentUpdatesRoute,
  DownloadBrochureRoute: DownloadBrochureRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  InvestmentBenefitsRoute: InvestmentBenefitsRoute,
  LocationConnectivityRoute: LocationConnectivityRoute,
  MasterPlanRoute: MasterPlanRoute,
  Phase2OverviewRoute: Phase2OverviewRoute,
  PlotSizesPricingRoute: PlotSizesPricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
